#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
no_color='\033[0m'

echo -e "\n${yellow}Executing pre-commit hook...${no_color}\n"

# npx prettier --write .
# npm run lint
npx lint-staged
git add .

FILES_PATTERN='\.(js)(\..+)?$'
FORBIDDEN='console\.[clear|dir|log|info|warn|error]'


echo -e "${green}Git pre-commit hook was successful!${no_color}\n"
echo \"${green} [Husky] pre-commit\"
npx lint-staged
echo -e "${green}Git pre-Commit hook was successful!${no_color}\n"
echo -e "${green} [Husky] pre-commit"


